title: LI Siyuan's Homepage 
page-top-title: LI Siyuan
top-section-bg-text: Be what you wanna be
home-subtitle: LI Siyuan&ensp;|&ensp;Homepage
copyright-text: '&copy; LI Siyuan 2025. All Rights Reserved.'
